---
title: "ELN Naming Application"
author: "Alistair Grevis-James <alistair.grevis-james@csl.com.au>"
date: "25/01/2018"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
#Adding the libraries
library(shiny)
library(data.tree)
library(rclipboard)
```

```{r, echo=FALSE}
#Creating the Root Node
D831 <- Node$new("D831")
```

```{r, echo=FALSE}
#Creating the Fundamental Technique Nodes

#HPLC
  FundamentalTechnique <- D831$AddChild("High Pressure Liquid Chromatography")
  FundamentalTechnique$tag <- 'HPLC'
    
  Methodology <- FundamentalTechnique$AddChild("Size Exclusion")
  Methodology$tag <- 'SE'
      Analyte <- Methodology$AddChild("Analyte1SE")
      Analyte$tag <- ("A1SE")
      Analyte <- Methodology$AddChild("Analyte2SE")
      Analyte$tag <- ("A2SE")
      
    Methodology <- FundamentalTechnique$AddChild("Cation Exchange")
    Methodology$tag <- 'CE'
      Analyte <- Methodology$AddChild("Analyte1CE")
      Analyte$tag <- ("A1CE")
      Analyte <- Methodology$AddChild("Analyte2CE")
      Analyte$tag <- ("A2CE")
      
    Methodology <- FundamentalTechnique$AddChild("Anion Exchange")
    Methodology$tag <- 'AE'
      Analyte <- Methodology$AddChild("Analyte1AE")
      Analyte$tag <- ("A1AE")
      Analyte <- Methodology$AddChild("Analyte2AE")
      Analyte$tag <- ("A2AE")

# Electrophoresis
  FundamentalTechnique <- D831$AddChild("Electrophoresis")
  FundamentalTechnique$tag <- 'EP'
    Methodology <- FundamentalTechnique$AddChild("EP Method 1")
    Methodology$tag <- 'EPMethod1'
      Analyte <- Methodology$AddChild("Analyte1")
      Analyte$tag <- ("A1")
      
# Cell-Based
  FundamentalTechnique <- D831$AddChild("Cell-Based")
  FundamentalTechnique$tag <- 'CB'
    Methodology <- FundamentalTechnique$AddChild("Size Exclusion")
    Methodology$tag <- 'SE'
      Analyte <- Methodology$AddChild("Analyte1")
      Analyte$tag <- ("A1")

# Mass Spectrometry
  FundamentalTechnique <- D831$AddChild("Mass Spectrometry")
  FundamentalTechnique$tag <- 'MS'
    Methodology <- FundamentalTechnique$AddChild("MS Method 1")
    Methodology$tag <- 'MSMethod1'
      Analyte <- Methodology$AddChild("Analyte1")
      Analyte$tag <- ("A1")


# 'Polymerase Chain Reaction':('Polymerase Chain Reaction','PCR'),
# 'Potency / Interaction':('Potency / Interaction','PI'),
# 'Crystallography':('Crystallography','CR'),
#  'Protein Concentration':('Protein Concentration','ProteinConc')}
      
      
      
```

```{r, echo=FALSE}
#Printing the Tree
print(D831)
#print(FundamentalTechnique$tag)
```

```{r, echo=FALSE}
#Adding the Projects
projects = c('', 'CSL689', 'CSL312', 'CSL346')
```

```{r, echo=FALSE}
# Create an empty c
techs = c('')
for (node in D831$children)
{ 
  techs <- c(techs, node$name) 
}

#Print list to confirm
#print(techs)
```



```{r, echo=FALSE}

# Define UI for application that draws a histogram
ui <- bootstrapPage(
   
   rclipboardSetup(),
  
   # Application title
   titlePanel("Proof of Concept Naming App"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         dateInput(
           inputId = "date",
           label = "Select Date of Analysis",
           value = Sys.Date(),
           format = "yyyy-mm-dd"),
         
         selectInput(inputId = "project",
                     label = "Select CSL Project",
                     choices = projects),
         
         uiOutput("techniqueInput"),
         uiOutput("methodInput"),
         uiOutput("analyteInput"),
         uiOutput("stringInput"),
         uiOutput("clip"),
         width = 8),
      
      # Show a plot of the generated distribution
      mainPanel()
   )
)

# ADD COMMENT
server <- function(input, output) {
   
  output$techniqueInput <- renderUI({
     if (input$project != '')
     {
       selectInput(inputId = "technique",
                   label = "Select Fundamental Technique",
                   choices = techs
       )
     }
      else
      {
        selectInput(inputId = "technique",
                    label = "Select Fundamental Technique",
                    choices = c('')
        )
      }
  })
  
  output$methodInput <- renderUI({
    
    techName = input$technique
    if (techName != '')
    {
      techNode = Navigate(D831, techName)
      
      methods <- c('')
      for (node in techNode$children)
      { 
        methods <- c(methods, node$name) 
      }
      
      selectInput(inputId = "method",
                  label = "Methodology",
                  choices = methods
      )
    }
    else
    {
      selectInput(inputId = "method",
                  label = "Methodology",
                  choices = c('')
      )
    }
    
  })
  
  output$analyteInput <- renderUI({
    
    techName = input$technique
    if (techName != '')
    {
      techNode = Navigate(D831, techName)
      
      methodName = input$method
      
      if (methodName != '')
      {
        methodNode = Navigate(techNode, methodName)
      
        analytes <- c('')
        for (node in methodNode$children)
        { 
          analytes <- c(analytes, node$name) 
        }
        
        selectInput(inputId = "analyte",
                    label = "Analyte",
                    choices = analytes
        )
      }
      else
      {
        selectInput(inputId = "analyte",
                    label = "Analyte",
                    choices = c('')
        )
      }

    }
    else
    {
      selectInput(inputId = "analyte",
                  label = "Analyte",
                  choices = c('')
      )
    }
    
  })
  
  output$stringInput <- renderUI({
    
    dateString = format(input$date, format="%Y%m%d")
    project = input$project
    
    techName = input$technique
    techNode = Navigate(D831, techName)
    if (techName != '')
    {
      techName = techNode$tag
    }
    else
    {
      techName = ''
    }
    
    methodName = input$method
    methodNode = Navigate(techNode, methodName)
    
    if (methodName != '')
    {
      methodName = methodNode$tag
    }
    else
    {
      methodName = ''
    }

    analyteName = input$analyte
    analyteNode = Navigate(methodNode, analyteName)
    
    if (analyteName != '')
    {
      analyteName = analyteNode$tag
    }
    else
    {
      analyteName = ''
    }
    
    project = sub("CSL","",project)
    str = paste(dateString, project, techName, methodName, analyteName, sep = "_")
    str = sub("_+$","",str)
  
    
    #Need a function to append _ only when selection is made
    textInput(inputId = "string",
              label = "Experiment Name",
              value = str
    )
  })
  
  output$clip <- renderUI({
    rclipButton("clipbtn", "Copy to Clipboard", input$string, icon("clipboard"))
  })

}

# Run the application 
shinyApp(ui = ui, server = server, options=list(height = 620))
```
 














